[package]
name  = "gr"
version = "0.0.1"
authors = ["Mark S. Baranowski"]
build="build.rs"


[lib]
name = "gr"
path = "src/gaol.rs"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.62"
packed_simd = "0.3.3"

[build-dependencies]
cc = "1.0.45"

